Our SETs tankless water heater is a piece of shit. It is constant power, set by the manual adjustment of a potentiometer. This is an awful design, as it means that the outlet temperature is flow rate dependent. So if you turn on the faucet at a low flow, you'll get scalding hot water, and if you turn on the high flow shower, you'll get cold water.

My plan is to replace the control circuit with my own Arduino.

* Hardware review
4 5500W heating elements - RC03205524 (https://hdsupplysolutions.com/p/apcom-electric-water-heater-element-240-volt-5-500-watts-p208702)
4 thermostatic switches - NGT L50 434812 6A06 (https://www.wbparts.com/rfq/5930-01-605-2892.html)
4 thyristors - Q6040J7 stays on after gate current removed (https://www.littelfuse.com/~/media/electronics/datasheets/switching_thyristors/littelfuse_thyristor_qxx40xx_datasheet.pdf.pdf)
** 4 Optoisolators - MOC3062 605Q (https://pdf1.alldatasheet.com/datasheet-pdf/view/5042/MOTOROLA/MOC3062.html)
pin 1 is input pin.

** How it works
The sensor at the inlet detects water flow and turns on the circuit with 5V.
Thyristors are used to control power to each of the heating elements, and optoisolators are used to supply gate voltage
Overheating is prevented by four thermostatic switches that open the heater circuit when temperature reaches ...
The exit temperature is measured why?
Potentiometer sets heat demand

** Math
each heater = 5500W = 5500 J/s
volumetric flow rate is 2 gpm (3.75 liter/min) = .0625 L/s = 0.0000625 m3
rho water = 1000 kg/m3
mass flow rate = .0625 kg/s
cp water = 4.2 kJ/kg*K
dT = (100F - 70F) = (310K - 294K) = 16K

Q = m * cp * dT
Q = .0625 kg/s * 4.2 kJ/kgK * 16 K = 4.2 kJ/s = 4200 J/s

therefore, one heater more than exceeds the capacity of the shower on a typical day

More extreme dT,
dT = (100F - 40F) = (310K - 277K) = 33K
Q = .0625 kg/s * 4.2 kJ/kgK * 33 K = 8.66 kJ/s = 8660 J/s

On a very cold day almost 2 heaters are needed.



* Phase 1 - Monitor
Monitor all sensors with Arduino

* Phase 2 - Existing Control
6/19/21 able to turn on the heaters. They are incredibly overpowered. A single heater will overheat the system in 5 seconds. It's difficult to control without a flow sensor at the inlet, allowing the calculation of how much power to input. The Temp sensor at the outlet has enough lag that the heaters will melt the system before it shows the temp. I can see why they had such a hard time with low flow. I'm not sure it's solvable without a flow meter at the inlet.
6/21/21 did more pid tuning today. No amount of tuning is going to make up for the lag between heater and thermistor in a low flow condition. Need a flow sensor.

fix by cutting 3/4" copper pipe and soldering the following sandwich:
3/4 to 1/2 reducer
1/2 copper x 1/2 FIP adapter
flow sensor
1/2 FIP adapter x 1/2 copper
1/2 to 3/4 reducer

https://www.homedepot.com/p/Everbilt-3-4-in-x-1-2-in-Copper-Pressure-Fitting-x-Cup-Reducer-C6002HD3412/100343698
https://www.homedepot.com/p/Everbilt-1-2-in-Copper-Pressure-Cup-x-FIP-Female-Adapter-Fitting-C603HD12/100344660
* Arduino Circuit
A0 - exit thermistor
A1 - inlet thermistor
D13 - Flow meter
9 - Heater 4
6 - Heater 3
5 - Heater 2
3 - Heater 1

** Software plan
There may not be a need for PID control as there is very little lag between input and output.
Q = m x cp x dT

1. Measure Tout
2. Set power
